idf_component_register(
    SRCS
        "main.c"
        "cmd_sniffer.c"
        "config.c"
        "events.c"
        "led.c"
        "serial_logger.c"
    PRIV_REQUIRES
        console
        esp_driver_gpio
        esp_event
        esp_timer
        esp_wifi
        nvs_flash
    INCLUDE_DIRS
        "."
)
