idf_component_register(
    SRCS
        "main.c"
        "cmd_sniffer.c"
        "cmd_pcap.c"
        "config.c"
        "ethernet.c"
        "events.c"
        "led.c"
        "mqtt.c"
        "ota.c"
        "sdcard.c"
        "serial_logger.c"
        "spi.c"
        "temperature.c"
    PRIV_REQUIRES
        app_trace
        app_update
        console
        esp_driver_gpio
        esp_eth
        esp_https_ota
        esp_netif
        esp_wifi
        fatfs
        nvs_flash
    INCLUDE_DIRS
        "."
)

